### ISSUE TITLE
Do you want some help on docs for SDL_Gpu?

### ISSUE THREAD

**Issue by RandyGaul** [thatcosmonaut/SDL#166]
I'm going to give the API a try and implement my cross-platform 2D renderer over in a small game creation framework that I maintain. Are you interested in PRs for in-code comments and documentation editing? I'm a fan of SDL style documentation and can match the aesthetic and intent, here's a reference: https://randygaul.github.io/cute_framework/#/

**Comment by thatcosmonaut** [comment]
We've documented SDL_gpu.h quite thoroughly but if you find somewhere that it is very deficient feel free to submit a PR. I will only note that I would respectfully decline minor edits at this point because we are hurrying to get the API fully approved before SDL3's public release and I do not want to waste time looking at those.

**Comment by RandyGaul** [comment]
Gotcha sounds like it’s good for now then. Thanks!
