### ISSUE TITLE
Keep Set/Get for transfer buffers?

### ISSUE THREAD

**Issue by flibitijibibo** [thatcosmonaut/SDL#17]
Might be redundant now that we have map/unmap :shrug:

**Comment by TheSpydog** [comment]
Been thinking on this some more. I don't think we should have both Set/Get and Map/Unmap, because it doesn't make sense to have two ways to do the exact same thing. However, they both have clear advantages and disadvantages...

**Pros of Set/Get:**
- We can perform bounds-checking internally, protecting the client from screwing up memory operations.
- We control the internals. If we ever need to do anything horrendous to support setting/getting data on a particular backend, we can hide our sins from the client.

**Cons of Set/Get:**
- Always requires an intermediate copy when reading data.
- There are limits to our ability to bounds-check. While we can protect against over-writes, we can't protect against over-reads. If you read 5KB worth of buffer into a 1 byte destination address, we can't do anything to stop you.

**Pros of Map/Unmap:**
- Gives you direct memory access to do as you please.
- No copies are needed for readback.
- The client can implement their own "safe" Set/Get on top of Map/Unmap, but not the other way around!

**Cons of Map/Unmap:**
- It's very easy to make mistakes when dealing with raw memory on the client side.
- Writing directly into raw memory is awkward in some languages -- even in C it requires funky pointer arithmetic.

A hypothetical best-of-both-worlds solution would be to provide a `SetData` function (to get the benefits of bounds-checking), and a `MapForRead` function (that allows you to read without copies). It seems a bit strange to split the API like this though.

If we're picking one or the other of our existing options, I'd say going with Map is the better route. It's more flexible, and as mentioned above, you can pretty easily write your own convenience wrapper on top of it if you don't want to deal with pointer arithmetic or raw `SDL_memcpy` calls when writing data.

**Comment by flibitijibibo** [comment]
I would go with map too - it might even be possible to simplify set/get to be macros or forced inline functions, but that's sort of why they're not all that helpful to begin with. As long as PlayStation can support map I don't think we'll need to worry about other backends.

**Comment by flibitijibibo** [comment]
Honestly we've gotten pretty far in and we actually use these functions a _lot_ - they may not be optimal but it's _definitely_ useful just based on what we've been writing, so unless this gets picked at during external review we can keep this.

**Comment by thatcosmonaut** [comment]
I changed my mind: https://github.com/thatcosmonaut/SDL/pull/144
