### ISSUE TITLE
D3D12 Fence Leak

### ISSUE THREAD

**Issue by thatcosmonaut** [thatcosmonaut/SDL#204]
The implementation is leaking ID3D12Fence references somewhere.

**Comment by TheSpydog** [comment]
Did some investigation and found that we're leaking because fence refcounts are too _low_. When we acquire a fence in `D3D12_Wait`, we're not incrementing its refcount, so when we release it, the refcount goes negative. This results in `SDL_AtomicDecRef` returning false and the fence never getting released to the pool.

Incrementing the ref count near the top of `D3D12_Wait` seems to fix this for me, but you may want to do a quick audit of the inc/dec ref calls just to be sure we're not missing something else.
