### ISSUE TITLE
Stencil issues on D3D11 (cycling issue)

### ISSUE THREAD

**Issue by RandyGaul** [thatcosmonaut/SDL#238]
I feel kind of bad for logging so many D3D11 bugs :(

I was creating some sample code for stencils by rendering a white outline around a sprite. It worked easily on Vulkan/D3D12, though D3D11 has some flickering issues. It looks a bit like screen tearing, but most frames the outline isn't cleared to white whatsoever. Renderdoc captures for the 3 backends attached below. First gif is D3D12/Vulkan, second shows odd flickering on D3D11. Sample [program here](https://github.com/RandyGaul/cute_framework/blob/gpu/samples/outline_stencil.cpp).

![outline](https://github.com/user-attachments/assets/16505ed5-3fbc-4181-9b4c-defc84d0ca1b)
![outline_bug](https://github.com/user-attachments/assets/344f6845-dd9e-49c5-bb74-860cf01d5458)

[rdc.zip](https://github.com/user-attachments/files/16739142/rdc.zip)

**Comment by RandyGaul** [comment]
Ah, this goes away on D3D11 if I disable cycling on the depth/stencil target in `SDL_GpuDepthStencilAttachmentInfo`. Does this mean I'm incorrectly using cycling? Why wouldn't this negatively affect D3D12 or Vulkan?

**Comment by RandyGaul** [comment]
https://github.com/RandyGaul/cute_framework/blob/master/samples/outline_stencil.cpp

**Comment by thatcosmonaut** [comment]
D3D11 capture is showing shader errors:
![Capture](https://github.com/user-attachments/assets/d03a5c45-0238-4466-99ed-f39fd0c3f125)

**Comment by thatcosmonaut** [comment]
Upon closer inspection, the D3D11 uniform values are incorrect on the first draw call... looking into it.

**Comment by thatcosmonaut** [comment]
Renderdoc stuff was a false alarm, looks like a bug on their end.

This patch should fix your issue: https://github.com/thatcosmonaut/SDL/pull/239

The example worked on D3D12 and Vulkan because those backends ignore the cycle bool if the load op is set to LOAD. The patch I linked makes it so the D3D11 backend does this too. 

Fundamentally though, the problem is that you are beginning a new render pass on each of your draw calls. This is pretty much the worst case scenario for performance. You should only begin and end a render pass when you actually need to change the texture that is being rendered to. 

The reason we ignore the cycle param on LOAD is because it does not make sense to cycle and load at the same time. I strongly recommend that you read the NOTE ON CYCLING section in `SDL_gpu.h`.

**Comment by thatcosmonaut** [comment]
Upon further consideration I've decided that we should just assert when the client requests to cycle and load at the same time.

**Comment by RandyGaul** [comment]
The asserts are quite helpful. As for the NOTE ON CYCLING, I've read it probably 20 times and don't really think it's sufficient. I have given some prior feedback on this as well in the big SDL PR topic that seems to have been ignored. Moving forward I would expect others to have similar trouble reading and understanding all its implications as-is.

**Comment by thatcosmonaut** [comment]
> Moving forward I would expect others to have similar trouble reading and understanding all its implications as-is.

I hear you - I'll queue up a detailed blog post about this topic. It's definitely the most unique and nuanced concept of our API

> Edit: On render passes -- Thanks for taking a look at my code there. The draw calls are batched and only issue new render passes for different textures, as you recommended. It seems maybe I just need to alter the code to _not_ cycle if the user wants to load prior contents.

That's what you should do, but the example you sent me was definitely beginning a new render pass each call even though the target texture was not changing.
