### ISSUE TITLE
Document required descriptor set annotations

### ISSUE THREAD

**Issue by thatcosmonaut** [thatcosmonaut/SDL#64]
Shader resources and uniform buffers have to be declared using a particular descriptor set order in the shader source to be usable with Vulkan. (Is this also true for Metal?) We should document this in the header so that people don't have to look at the examples to find them.

**Comment by TheSpydog** [comment]
Can confirm that Metal definitely needs some special documentation for expected resource order. Uniforms, readonly storage buffers, read-write storage buffers, and vertex buffers all share the same "buffer" address space and are expected to be in a particular order. Similarly, readonly/read-write storage textures and regular textures share a mutual "texture" address space.

I'll write up the Metal docs once the Vulkan docs have been added in, since I imagine they'll share the same comment block.
